# Generated by Django 4.2.26 on 2026-05-03 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VwHospitalBedSummary',
            fields=[
                ('hospital_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=80)),
                ('total_beds', models.IntegerField()),
                ('available', models.IntegerField()),
                ('occupied', models.IntegerField()),
                ('maintenance', models.IntegerField()),
            ],
            options={
                'db_table': 'vw_hospital_bed_summary',
                'managed': False,
            },
        ),
    ]
