# Generated by Django 4.2.26 on 2026-05-11 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicore', '0002_vwhospitalbedsummary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admission',
        ),
        migrations.DeleteModel(
            name='Blooddonation',
        ),
    ]
